
language: node_js
node_js: 5
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp-cli
script:
- npm run browser-build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
