
language: node_js
node_js: 10
cache:
  directories:
  - node_modules
before_script:
  - npm install
script:
  - cp ./dist/* .
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
